### ISSUE TITLE
Queues rework causes IP reuse error

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#317]
```
fatal: [sf-1]: FAILED! => {"changed": false, "meta": "Failed to parse JSON:\n[[command: sf-client --json instance create cirros_netspec 1 1  -D size=8,base=cirros  -N network_uuid=cbfc5d6b-0fd4-4861-940f-c9ef33dee81c,address=192.168.242.66,macaddress=02:42:4d:0a:86:fe -p  sf-1 ]]\n[[stdout: ERROR: Resource in use: address 192.168.242.66 in use\n]]\n[[stderr: ]]", "msg": "Error manipulating instance", "params": {"cpu": "1", "disks": null, "diskspecs": ["size=8,base=cirros"], "name": "cirros_netspec", "networks": null, "networkspecs": ["network_uuid=cbfc5d6b-0fd4-4861-940f-c9ef33dee81c,address=192.168.242.66,macaddress=02:42:4d:0a:86:fe"], "placement": "sf-1", "ram": "1", "ssh_key": "", "state": "present", "user_data": "", "uuid": null}}
```

**Comment by mikalstill** [comment]
This is a bug in the ansible CI:

```
#########################################
# Scenario: try other ways to specify networks
#########################################

- hosts: sf-1
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh

  tasks:
    - name: Try more detailed network specifications
      sf_instance:
        name: "cirros_netspec"
        cpu: 1
        ram: 1
        diskspecs:
          - size=8,base=cirros
        networkspecs:
          - network_uuid={{net_one_uuid}},address=192.168.242.66,macaddress=02:42:4d:0a:86:fe
        ssh_key: ""
        user_data: ""
        placement: "{{inventory_hostname}}"
      register: instance_create_out
```

What if we already used .66 for another VM randomly allocated that IP in previous tests in this file?

I'm not sure how to resolve this right now...
